// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardGrid: typeof import('ant-design-vue/es')['CardGrid']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    ACol: typeof import('ant-design-vue/es')['Col']
    AInput: typeof import('ant-design-vue/es')['Input']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARow: typeof import('ant-design-vue/es')['Row']
    ATag: typeof import('ant-design-vue/es')['Tag']
    Card: typeof import('./src/components/card.vue')['default']
    Fold: typeof import('./src/components/fold.vue')['default']
    Item: typeof import('./src/components/core/item.vue')['default']
    QuestionItem: typeof import('./src/components/core/QuestionItem.vue')['default']
    Questions: typeof import('./src/components/core/Questions.vue')['default']
    QustionItem: typeof import('./src/components/core/QustionItem.vue')['default']
    Submit: typeof import('./src/components/core/submit.vue')['default']
  }
}
